import {
  Search,
  Braces,
  Image,
  FileText,
  KeyRound,
  Link2,
  Binary,
  FileCode,
  Type,
  Code2,
  CaseSensitive,
  Box,
  Regex,
  Package,
  Clock,
  Fingerprint,
  Shield,
  Palette,
  Paintbrush,
  FileKey,
  Minimize2,
  Megaphone,
  Bot,
  Map,
  CalendarClock,
  Wrench,
  type LucideIcon,
} from "lucide-react";

export const TOOL_ICON_MAP: Record<string, LucideIcon> = {
  "seo-meta-generator": Search,
  "json-formatter": Braces,
  "image-resizer": Image,
  "lorem-ipsum": FileText,
  "password-generator": KeyRound,
  "url-encoder": Link2,
  "base64-encoder": Binary,
  "markdown-previewer": FileCode,
  "word-counter": Type,
  "html-entity": Code2,
  "case-converter": CaseSensitive,
  "box-shadow-generator": Box,
  "regex-tester": Regex,
  "object-to-json": Package,
  "timestamp-converter": Clock,
  "uuid-generator": Fingerprint,
  "hash-generator": Shield,
  "color-converter": Palette,
  "css-gradient-generator": Paintbrush,
  "jwt-decoder": FileKey,
  "css-minifier": Minimize2,
  "utm-builder": Megaphone,
  "robots-txt-generator": Bot,
  "sitemap-generator": Map,
  "cron-helper": CalendarClock,
};

export function getToolIcon(slug: string): LucideIcon {
  return TOOL_ICON_MAP[slug] ?? Wrench;
}
