import type { ToolConfig } from "./types";

export const TOOLS: ToolConfig[] = [
  {
    id: 1,
    slug: "seo-meta-generator",
    name: "SEO Meta Tag Generator",
    description: "Generate optimized title, description, and Open Graph tags.",
    category: "SEO",
  },
  {
    id: 2,
    slug: "json-formatter",
    name: "JSON Formatter & Validator",
    description: "Format, minify, and validate JSON with clear error messages.",
    category: "Developer",
  },
  {
    id: 3,
    slug: "image-resizer",
    name: "Image Resizer & Compressor",
    description: "Resize and compress images in-browser with canvas.",
    category: "Media",
  },
  {
    id: 4,
    slug: "lorem-ipsum",
    name: "Lorem Ipsum Generator",
    description: "Generate placeholder text by words, sentences, or paragraphs.",
    category: "Content",
  },
  {
    id: 5,
    slug: "password-generator",
    name: "Password & API Key Generator",
    description: "Create secure passwords and API keys with custom rules.",
    category: "Security",
  },
  {
    id: 6,
    slug: "url-encoder",
    name: "URL Encoder / Decoder",
    description: "Encode and decode URI components safely.",
    category: "Developer",
  },
  {
    id: 7,
    slug: "base64-encoder",
    name: "Base64 Encoder / Decoder",
    description: "Convert text and files to and from Base64.",
    category: "Developer",
  },
  {
    id: 8,
    slug: "markdown-previewer",
    name: "Markdown to HTML Previewer",
    description: "Live preview Markdown rendered as HTML.",
    category: "Content",
  },
  {
    id: 9,
    slug: "word-counter",
    name: "Word & Character Counter",
    description: "Count words, characters, lines, and reading time.",
    category: "Content",
  },
  {
    id: 10,
    slug: "html-entity",
    name: "HTML Entity Encoder / Decoder",
    description: "Encode and decode HTML entities for safe output.",
    category: "Developer",
  },
  {
    id: 11,
    slug: "case-converter",
    name: "Case Converter",
    description: "Convert text to upper, lower, title, and slug case.",
    category: "Content",
  },
  {
    id: 12,
    slug: "box-shadow-generator",
    name: "CSS Box Shadow Generator",
    description: "Visual box-shadow builder with live CSS output.",
    category: "Design",
  },
  {
    id: 13,
    slug: "regex-tester",
    name: "Regex Tester & Matcher",
    description: "Test regular expressions with match highlighting.",
    category: "Developer",
  },
  {
    id: 14,
    slug: "object-to-json",
    name: "JS Object to JSON Converter",
    description: "Parse JavaScript object literals into valid JSON.",
    category: "Developer",
  },
  {
    id: 15,
    slug: "timestamp-converter",
    name: "Timestamp / Epoch Converter",
    description: "Convert Unix timestamps to human-readable dates.",
    category: "Developer",
  },
  {
    id: 16,
    slug: "uuid-generator",
    name: "UUID Generator",
    description: "Generate v4 UUIDs instantly for APIs, databases, and testing.",
    category: "Developer",
  },
  {
    id: 17,
    slug: "hash-generator",
    name: "Hash Generator (SHA-256)",
    description: "Create SHA-256 hashes from text using Web Crypto — client-side only.",
    category: "Security",
  },
  {
    id: 18,
    slug: "color-converter",
    name: "Color Converter",
    description: "Convert colors between HEX, RGB, and HSL with live preview.",
    category: "Design",
  },
  {
    id: 19,
    slug: "css-gradient-generator",
    name: "CSS Gradient Generator",
    description: "Build linear and radial gradients with live preview and CSS output.",
    category: "Design",
  },
  {
    id: 20,
    slug: "jwt-decoder",
    name: "JWT Decoder",
    description: "Decode JSON Web Token headers and payloads safely in the browser.",
    category: "Security",
  },
  {
    id: 21,
    slug: "css-minifier",
    name: "CSS / HTML Minifier",
    description: "Strip comments and whitespace from CSS or HTML for production.",
    category: "Developer",
  },
  {
    id: 22,
    slug: "utm-builder",
    name: "UTM Campaign Link Builder",
    description: "Build tracked marketing URLs with UTM parameters for analytics.",
    category: "SEO",
  },
  {
    id: 23,
    slug: "robots-txt-generator",
    name: "Robots.txt Generator",
    description: "Generate robots.txt rules for crawlers with common presets.",
    category: "SEO",
  },
  {
    id: 24,
    slug: "sitemap-generator",
    name: "XML Sitemap Generator",
    description: "Create a valid XML sitemap from your list of page URLs.",
    category: "SEO",
  },
  {
    id: 25,
    slug: "cron-helper",
    name: "Cron Expression Helper",
    description: "Parse cron syntax and describe when jobs will run.",
    category: "Developer",
  },
];

export const TOTAL_TOOLS = TOOLS.length;

export function getToolBySlug(slug: string): ToolConfig | undefined {
  return TOOLS.find((t) => t.slug === slug);
}
